### ISSUE TITLE
Screen freezes on using 'password' function multiple times

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1275] opened 2015-02-09 07:53 UTC
Screen turns dark and freezes when 'password' function is used to create pop-ups.
When it is used multiple times in the same cell  as shown below, only the first pop-up appears and user is asked for the first input only and consequently the screen freezes
![single cell](https://cloud.githubusercontent.com/assets/9251570/6102548/65c6ab1a-b05e-11e4-8e3f-fa1b31593ab9.PNG)

When it is used in multiple cells, all the pop-ups appear and user is asked for all inputs but again the screen freezes after that.
![multiple cells](https://cloud.githubusercontent.com/assets/9251570/6102564/baf9775c-b05e-11e4-8d1a-b1771a9c8bd9.PNG)

**Comment by gordonwoodhull** [comment] 2015-02-09 14:58
Ah okay. The clue that it takes multiple `password` calls, is crucial. I think this is a duplicate of #371.

Since we have direct input now, we might consider dropping the dialog. But I'm not sure how to do the special case where the input is shown obscured - not sure how to detect this case on the server and not sure if ace supports the feature.

**Closed** 2015-02-11 17:41 UTC
Labels: bug, duplicate
