### ISSUE TITLE
Give users ability to fork a collection of notebooks, typically an entire directory

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1392] opened 2015-03-27 15:51 UTC
One use case for RCloud is in training.  The instructor prepares a set of lessons and then asks the class to fork the lessons.  Depending on how the instructor chose to do this there may be multiple levels in the name, which appear as directories/subdirectories (even though they are not).

Users would like to be able to fork groups of notebooks in one operation.

Multiple users have requested this.

In the attached picture the user would like to get everything under "HW-DS" and maintain the structure when forked (i.e., not flatten)

![image](https://cloud.githubusercontent.com/assets/1158095/6871202/fa731b48-d46e-11e4-8a8f-883a69633c41.png)

**Comment by gordonwoodhull** [comment] 2015-03-27 17:57
Thanks Marty, this is often requested and a duplicate of #1149. Will schedule it for 1.4

**Closed by gordonwoodhull** 2015-03-27 17:57 UTC
