### ISSUE TITLE
help for search

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1415] opened 2015-04-22 16:15 UTC
The syntax of the search is not intuitive, so it would be nice to have a quick help available directly from the search -- e.g., a "?" icon next to the search field that explains the rules

**Comment by gordonwoodhull** [comment] 2015-04-22 16:31
Yes. Duplicate of #521, and the data you are looking for is specifically 
http://lucene.apache.org/core/3_5_0/queryparsersyntax.html

**Closed by gordonwoodhull** 2015-04-22 16:31 UTC
Labels: enhancement
