### ISSUE TITLE
rserve.pid is broken

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1192] opened 2015-01-21 04:47 UTC
[root@zlts7224 rcloud]# ps -efwww | grep -i rserve | grep -v grep
root     128292      1  0 23:31 ?        00:00:00 /opt/app/R/lib64/R/library/Rserve/libs/RsrvSRV --RS-conf /opt/app/rcloud/conf/rserve.conf --vanilla --no-save
 
[root@zlts7224 rcloud]# cat run/rserve.pid
128288

**Comment by prateek05** [comment] 2015-01-21 22:13
It seems to be intact in Rserve-1.8-0
ID file is created before the server is forked ?
```
/* called once the server process is setup (e.g. after
   daemon fork for forked servers) */
static void RSsrv_init() {
	if (pidfile) {
		FILE *f = fopen(pidfile, "w");
		if (f) {
			fprintf(f, "%ld\n", (long) getpid());
			fclose(f);
		} else RSEprintf("WARNING: cannot write into pid file '%s'\n", pidfile);
	}
```
@s-u help!!!

**Comment by s-u** [comment] 2015-01-21 22:44
Ah, yes, caused by 8afaacc - `RSsrc_init()` needs to be moved as well, thanks.

**Comment by s-u** [comment] 2015-01-22 15:41
Should be now fixed on both Rserve branches.

**Closed by s-u** 2015-01-22 15:41 UTC
