### ISSUE TITLE
view.html not scrolling as expected

### ISSUE THREAD

**Issue by prattatx** [att/rcloud#1421] opened 2015-04-25 15:40 UTC
in view mode, scroll in center panel scrolls the panel. scrolling outside the center panel does not scroll the content. The two side panels do not scroll content, but are expected to scroll when in view mode.

**Comment by gordonwoodhull** [comment] 2015-04-25 16:32
Yes. Duplicate of #700

**Closed by gordonwoodhull** 2015-04-25 16:32 UTC
