### ISSUE TITLE
Unable to assign a notebook to group or private

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1664] opened 2015-09-16 08:29 UTC
steps to replicate:(RCloud-2 and RCloud local instance)
- Upload any **image/pdf** asset to a public notebook
- Try to make that notebook private or try to assign it to any group

following error message will be displayed 
![image_encrypt_error](https://cloud.githubusercontent.com/assets/9251570/9899893/7d0141b4-5c7a-11e5-9397-7748974d6eac.PNG)

However we can upload **image/pdf** assets to a notebook after assigning it to any group or making it private

**Comment by s-u** [comment] 2015-09-16 13:57
Duplicate of #1616

**Closed by s-u** 2015-09-16 13:57 UTC

**Comment by gordonwoodhull** [comment] 2015-09-16 14:08
@sanketd11, can you confirm this is with a large-ish (>400k) asset? 

Can you reproduce the bug with a smaller (~100k) asset?

**Comment by sanketd11** [comment] 2015-09-18 06:44
I am able to reproduce this bug with small size assets having sizes around  8 to 10 KB as well as with those having sizes greater than 400 KB.
