### ISSUE TITLE
Testing on RCloud local: Variable values are missing in workspace div 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1327] opened 2015-02-15 13:20 UTC
For the any variable with length equal or greater than two, only the variable name, its data type and length are displayed in workspace div. The values are missing for such variables 

![workspace div](https://cloud.githubusercontent.com/assets/9251570/6203347/11ff079a-b543-11e4-874a-9928fbd6746c.PNG)

the behavior is as expected for the variable with single value

**Comment by prateek05** [comment] 2015-02-15 15:02
It is by design the workspace viewer will only hold attributes of the object. 

At some point the df viewer will server the purpose of all viewer.

**Comment by gordonwoodhull** [comment] 2015-02-15 20:12
I also think it would be more helpful to show some of the values.  Not that they get everything right, but RStudio shows the first five values.

**Comment by prateek05** [comment] 2015-02-15 21:52
Hah! the reference PR does not show up here... 
https://github.com/att/rcloud/pull/1332

**Comment by gordonwoodhull** [comment] 2015-02-15 22:00
Right, github is funny about where it auto-links issue numbers.  Mentioning an issue number in a title doesn't do anything.  You have to refer to it in a comment (as well as the commit message).  Thanks!

**Comment by gordonwoodhull** [comment] 2015-02-15 22:58
Fixed by #1332

**Comment by gordonwoodhull** [comment] 2015-02-16 14:39
Reopening since #1332 was reverted.

**Comment by gordonwoodhull** [comment] 2015-02-22 08:30
fixed by a374fcf288e221524a10c3c843fa5da160a9a671

**Closed by gordonwoodhull** 2015-02-22 08:30 UTC
Labels: bug
