### ISSUE TITLE
Excess white space on left and right on large MAC monitors

### ISSUE THREAD

**Issue by aarthireddy** [att/rcloud#1251] opened 2015-02-05 18:36 UTC
On a 2560 pixel wide Mac monitor there is extra unused white space on the right and left side. Can we modify the max width parameter? You can see the white space on either side in the image below.
![screen shot 2015-02-05 at 12 35 23 pm 2](https://cloud.githubusercontent.com/assets/3835816/6066558/8e7fd136-ad33-11e4-8715-ae325c51e342.png)

**Comment by gordonwoodhull** [comment] 2015-02-05 18:37
Yes, duplicate of #655

**Comment by gordonwoodhull** [comment] 2015-02-05 18:38
Thanks for the report.

**Closed by gordonwoodhull** 2015-02-05 18:37 UTC
