### ISSUE TITLE
plots in a newly created cell close the RCloudDevice

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1670] opened 2015-09-22 18:14 UTC
for example,

```{r}
plot(1:10)
```

in one cell, and 

```{r}
locator(5)
```
in the next cell.

Error:
```
Error in locator(10) : plot.new has not been called yet
```

Succeeds when re-run.

**Comment by gordonwoodhull** [comment] 2015-10-03 19:59
I see this consistently on my local instance and rcloud-5. 

It seems like RCloud can also get "distracted" by other actions, like adding or changing another cell and running, and "forget" about the plot. Once the plot is rerun, locator works again.

**Comment by gordonwoodhull** [comment] 2015-10-03 20:03
Additionally, after this happens, cell manipulations (like edits or deletes) cause errors in the session div, apparently because they cause a `load_notebook_compute` which resets the session and tries to save the image:

```
Error: load_notebook_compute: Error in .session$RCloudDevice[[dev]]$pages[[page]] <- Cairo.snapshot(dev, :
attempt to select less than one element
R trace:
(function (dev, page, cmd = "img.url.final")
{
img <- Cairo.capture(dev)
did <- .session$RCloudDevice[[dev]]$id
payload <- if (cmd == "img.url.final" && isTRUE(Cairo.serial(dev) ==
.session$RCloudDevice[[dev]]$serial))
""
else dataURI(writePNG(img), "image/png")
if (is.na(page))
page <- .session$RCloudDevice[[dev]]$page + 1L
else .session$RCloudDevice[[dev]]$page <- page
.rc.oobSend(cmd, payload, rev(dim(img)), did, page)
if (!is.null(payload))
.session$RCloudDevice[[dev]]$pages[[page]] <- Cairo.snapshot(dev,
NA)
if (dev != dev.cur()) {
.rc.oobSend("dev.close", did)
.session$RCloudDevice[[dev]]$serial <- NULL
}
else .session$RCloudDevice[[dev]]$serial <- Cairo.serial()
TRUE
})(4L, 0L)
dev.off()
rcloud.reset.session()
rcloud.load.notebook(...)
fun(...)
attempt to select less than one element
at success (https://rcloud-5.research.att.com/js/rcloud_bundle.js:135:23)
From previous event:
at Object.RCloud.promisify_paths.v [as load_notebook_computeAsync] (https://rcloud-5.research.att.com/js/rcloud_bundle.js:141:54)
at Object.rcloud.refresh_compute_notebook (https://rcloud-5.research.att.com/js/rcloud_bundle.js:298:55)
at cb_ (https://rcloud-5.research.att.com/js/rcloud_bundle.js:3180:28)
From previous event:
at Object.result.remove_cell (https://rcloud-5.research.att.com/js/rcloud_bundle.js:3433:18)
at https://rcloud-5.research.att.com/js/rcloud_bundle.js:4511:64
at HTMLSpanElement.<anonymous> (https://rcloud-5.research.att.com/js/rcloud_bundle.js:4312:21)
at HTMLSpanElement.jQuery.event.dispatch (https://rcloud-5.research.att.com/lib/js/jquery-2.1.1.js:4409:9)
at HTMLSpanElement.jQuery.event.add.elemData.handle (https://rcloud-5.research.att.com/lib/js/jquery-2.1.1.js:4095:28)
```

**Comment by s-u** [comment] 2015-10-06 17:25
There are two issues here:

- The device has been closed so there is no plot to refer to. That is what the R-side error says and it's quite clear and as expected. It's a user error to try to interact on a non-existent plot.

- Once you try to operate on a non-existent device, RCloud will open a new one without any content (since there was nothing plotted in it). If you then try to ask for the content you get page 0 which confuses our bookkeeping code.

So it's easy to fix the latter, but that will only remove the JS error. The big question is why would anyone runt he locator after closing the device but before plotting anything. So far it doesn't seem to have anything to do with the locator AFAICS.

**Comment by gordonwoodhull** [comment] 2015-10-06 17:48
But I didn't close the device! It is exactly the code I describe above, and it works when I rerun the notebook.

**Comment by s-u** [comment] 2015-10-06 20:23
I have addressed the latter in the commit above.

However, there is a mystery in the first point -- a newly created cell closes the device immediately. When you run the cell once created in a fresh session, it works as expected. So the only time it breaks is when a new cell is created. Also it has nothing to do with locator, all commands fail - and you can check it with `dev.list()`. Finally, the device is alive and kicking when the cell is evaluated, i.e. `dev.list()` in the cell lists the device, running it after the cell comes out empty.

Do we know how the creation of the cell is different from any other execution?

**Comment by s-u** [comment] 2015-10-06 20:24
BTW: this is a really bad regression - I would classify it as major. Can it have something to do with the changes concerning contexts?

**Comment by gordonwoodhull** [comment] 2015-10-06 21:15
I agree it's severe.

The context changes aren't present here.

Here it is: the notebook is changed by the control process, and the compute process needs to be explicitly updated so that snapshots work - so there is an rcloud.load.notebook call there. 

Which resets.

**Comment by gordonwoodhull** [comment] 2015-10-06 21:18
Here:

```{js}
                    rcloud.refresh_compute_notebook(notebook.id);
```
https://github.com/att/rcloud/blob/bcdd1e394981504309c6ac76bf223170098f2950/htdocs/js/notebook/notebook_controller.js#L25

```{r}
rcloud.load.notebook <- function(id, version = NULL, source = NULL) {
  res <- rcloud.get.notebook(id, version, source)
  ulog("RCloud rcloud.load.notebook(",id,",",version,", user=", .session$username,"): ", if(res$ok) "OK" else "FAILED")
  if (res$ok) {
    .session$current.notebook <- res
    rcloud.reset.session()
  }
  res
}
```
https://github.com/att/rcloud/blob/develop/rcloud.support/R/rcloud.support.R#L84-L92

**Comment by gordonwoodhull** [comment] 2015-10-06 21:21
I have no clue why we're not losing all state every time the notebook is saved. `rcloud.reset.session` also contains

```{r}
  .close.session()
  .open.session()
```

**Comment by gordonwoodhull** [comment] 2015-10-06 21:22
I guess we need a load-notebook-without-blasting-the-session, eccch.

**Comment by gordonwoodhull** [comment] 2015-10-06 21:23
Here's the commit, "refresh compute notebook cache when control saves" 6513541bb9d166fc7bdabd62fae03f0c27ebc23c, I didn't notice that `rcloud.load.notebook` is doing a lot more than loading the notebook.

**Comment by gordonwoodhull** [comment] 2015-10-06 21:34
More evidence that compute really needs to pull notebooks from control.

**Comment by gordonwoodhull** [comment] 2015-10-06 23:17
Adding the parameter to `rcloud.load.notebook` for now.

**Closed** 2015-10-06 23:31 UTC
Labels: bug
