### ISSUE TITLE
cmd-click on "fork" kills the current session

### ISSUE THREAD

**Issue by s-u** [att/rcloud#2441] opened 2017-07-30 15:29 UTC
`<Cmd>`-click on "fork" is expected to open a new tab with the forked notebook, but instead it kills the current session and replaces it with a new session and the forked notebook.

**Comment by gordonwoodhull** [comment] 2017-07-30 15:50
Totally agree we should implement this, but every single one of these behaviors may be implemented by hand, so it's a feature request not a bug. (The only ctrl/cmd- behaviors that are automatic are straight links - anything invoking javascript is custom code.)

**Comment by s-u** [comment] 2017-07-31 15:17
Sorry, but bad, unexpected behavior is a bug in my book (official definition: "bug: an unexpected defect, fault, flaw, or imperfection"). It doesn't matter how it's implemented - the fact that those have to be implemented by hand is not an excuse - then it's yet another bug that any links changing the session are not being dealt with in a consistent way.

**Comment by gordonwoodhull** [comment] 2017-07-31 15:31
I don't mean it as an excuse. The goal should not be to assign blame, but to communicate to our team how to get the work done. 

If it's marked as a bug, I think that signals that the functionality exists but it doesn't work correctly. Versus marking as an enhancement means that new code needs to be written.

I'm sorry if you are frustrated by the current behavior, but please try to approach this as a developer, not as a grumpy user. We have enough of those. :)

**Comment by s-u** [comment] 2017-07-31 16:22
Grump, Grump :) But, seriously, this should then be fixed by making sure we use the same path for all links that may change the session so that the behavior is consistent. Right now it's not, so local fixes make less sense as we may see bugs where we missed it. Let me know if you want to file a separate issue on this.

**Comment by gordonwoodhull** [comment] 2017-07-31 16:24
I agree, but that would be easier to accomplish if I were allowed to work on the project. It's pretty hard to specify a refactoring for contractors to complete.

**Closed** 2017-11-21 20:19 UTC
Labels: enhancement
