### ISSUE TITLE
Newly created notebook is not showing up in discover page

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2032] opened 2016-06-06 09:04 UTC
The newly created notebook(empty notebook) is not displayed in Discover page. The notebook gets displayed only when the notebook contents are saved at least once

**Comment by gordonwoodhull** [comment] 2016-06-06 09:44
I argued in #2028 that showing new, unchanged notebooks is boring and useless. However, I guess it's surprising not to see them there, so we should show them anyway.

**Comment by gordonwoodhull** [comment] 2016-06-08 17:27
Fixed in #2047

**Comment by amithrb** [comment] 2016-06-23 10:38
This issue still persists on release-1.6/ 112bd78

**Comment by gordonwoodhull** [comment] 2016-06-24 05:06
I'm not seeing this currently.

**Comment by amithrb** [comment] 2016-06-24 06:48
@gordonwoodhull , Please try the following scenario:
- Refresh the URL of main page.
- Create new notebook.
- Go to discover page.

Unable to see the newly created notebook.
I can reproduce this issue on release-1.6/ 0cd33da.

**Comment by gordonwoodhull** [comment] 2016-06-24 07:00
Nope, I see the new notebook on the discover page.

Just to be sure, please verify the source of this function to make sure your server is up-to-date (sometimes it can be hard to completely kill and restart it):

![image](https://cloud.githubusercontent.com/assets/1366709/16330445/2dc27206-39b7-11e6-8243-b8f173a898dd.png)

**Comment by gordonwoodhull** [comment] 2016-06-24 07:00
`set.recently.modified.notebook` should do it.

**Comment by gordonwoodhull** [comment] 2016-06-24 07:06
Or if that checks out okay, please see if you can replicate the problem on rcloud-5, I just updated it.

**Comment by amithrb** [comment] 2016-06-24 08:29
I was able to reproduce it in rcloud-5.

**Comment by gordonwoodhull** [comment] 2016-06-24 08:32
I'm definitely not seeing it there, either. Is it possible that there is some odd time zone sorting problem and the notebook is actually displayed further down in the recent notebooks?

**Comment by amithrb** [comment] 2016-06-24 11:09
I have checked going further down in recent notebooks but, still not able to see it.
I will try to reproduce during WebEx call.

**Comment by gordonwoodhull** [comment] 2016-06-25 05:02
Okay, I am seeing this now, on a blank instance and on rcloud-5. 

There is no sign of some recently created or modified notebooks, even in the raw data returned to the page.

Being able to repro on a blank instance is very helpful.

**Comment by gordonwoodhull** [comment] 2016-06-30 06:51
I am no longer able to repro. On instances where there are a more than 100 notebooks, this could have been caused by #2136 which showed some arbitrary 100 notebooks in order of date, rather than the most recent.

#2154 describes an issue where the very first notebook created in a brand new DB does not appear.

@amithrb, please lmk if there are other cases where you still see this.

**Comment by amithrb** [comment] 2016-07-05 04:44
@gordonwoodhull , I am not able to reproduce this issue with latest commit 7e31525

**Comment by gordonwoodhull** [comment] 2016-07-05 04:50
Great! Thanks @amithrb!

**Closed by gordonwoodhull** 2016-07-05 04:50 UTC
Labels: bug
