### ISSUE TITLE
Key up on cell causes cursor to disappear when upper part of cell is hidden

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud#1900] opened 2016-04-13 17:35 UTC
Steps to reproduce:

1 -  Increase height of notebook cell so that its height is greater than the available height of the middle column:

![image](https://cloud.githubusercontent.com/assets/2493614/14503057/44107eb6-01a6-11e6-9965-a1e889d58e65.png)

Observe that a vertical scrollbar appears as expected.

2 - Now keyup _or_ keydown, and _hey presto_, your cursor disappears.

**Comment by shaneporter** [comment] 2016-04-13 17:43
The editor has a `autoScrollEditorIntoView` property which usually fixes this issue. However, setting it in RCloud causes even bigger problems.

**Comment by gordonwoodhull** [comment] 2016-04-14 13:06
Yeah, I don't think Ace even knows about the scrolling anymore, so if we go with your solution to long cells, we will probably have to implement this ourselves. 

I am pretty sure there will be a way to subscribe to cursor events in Ace. Not that I've done the research, but it has a rich API, even though it's not fully documented. [Official documentation.](https://ace.c9.io/#nav=api)

Unfortunately, implementing this may be more work than the original fix, but that's just the nature of UI engineering. I think it's really important that you keep on top of the issues for this new behavior, because we don't to end up having to reverse the fix at the last minute.

**Comment by shaneporter** [comment] 2016-04-14 13:33
If I set `autoScrollEditorIntoView` to `true` **and** remove the static toolbar, selection bar, selection toolbar **and** remove the padding on the body, it works great :)

I took a look at the cursor handling, and although it's not that difficult to ascertain where it is, knowing whether it is 'invisible' is more difficult. Yuck!

**Comment by gordonwoodhull** [comment] 2016-04-14 13:42
Haha, I see, so Ace will automatically scroll its parent, as long as it's pretty much the only thing in its parent? Zoiks. Is this one of those situations where adding another intermediate div can help?

Well, I don't mean to throw more distracting and useless ideas at you. I'm sure you'll figure it out. 

It's great to know that Ace was designed to be used in this way, really tall and with scrolling implemented by the parent.

**Comment by gordonwoodhull** [comment] 2016-04-27 11:44
fixed by #1934

**Closed by gordonwoodhull** 2016-04-27 11:44 UTC
Labels: bug
