### ISSUE TITLE
Some RCloud features stop working 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1989] opened 2016-05-20 08:14 UTC
![image](https://cloud.githubusercontent.com/assets/9251570/15421039/dc3c3914-1e8e-11e6-9a13-ce118eabc87e.png)

Some of the RCloud features stop working when the above given error appears in the Terminal/consol.
The features include Undo/Redo, shell cell execution, file export as R source, etc

shell cell execution throws following error after execution

![image](https://cloud.githubusercontent.com/assets/9251570/15421229/b2573152-1e8f-11e6-98de-cd24ecb42036.png)

Rserve needs a fresh_start for the above mentioned features to work.

**Comment by s-u** [comment] 2016-05-23 18:41
In general, it means you did something that broke some outgoing connection in R. R does error out what you do that - it's a "feature" of R, not really related to RCloud.

However, the error you're showing is entirely unrelated - it seems that you `TEMPDIR` is gone - which is indeed a fatal error since it should never happen (R will break in many ways when that happens - by design).

**Comment by s-u** [comment] 2016-05-23 20:04
I think `SIGPIPE` is a red herring here - it's really just #1770 - I'll close this as duplicate unless someone can de-trangle the two.

**Closed by s-u** 2016-05-23 20:04 UTC
