### ISSUE TITLE
Error, after clicking on link from the asset div

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1461] opened 2015-05-21 09:15 UTC
This issue was observed in RCloud local instance.
Upload CSV file to the newly created notebook. The uploaded file gets displayed under asset div.
When we click on 'link' from the asset div, the following error is displayed in new tab of the browser (only for the first time).

![error_after_clicking_on_linkfromasset_div](https://cloud.githubusercontent.com/assets/10941328/7745164/a72032ea-ffc6-11e4-83b7-c2da5749746a.PNG)

**Comment by gordonwoodhull** [comment] 2015-06-10 18:04
I'm not able to reproduce this. Uploading a file should immediately create the asset in the gist, so I don't know how this could happen.

@Prateek032, are you still seeing this?

**Comment by gordonwoodhull** [comment] 2015-06-25 02:35
@Prateek032, I'm still not able to repro. 

It looks like somehow the file is not uploaded by the time the tab is opened. Not sure how this could happen, since the link should only be updated once the round-trip has happened. GitHub does have some concurrency issues (or optimizations perhaps) and they've advised me not to count on a query working until a second after a command.

If you see it again, please try reloading the page to see if it appears a little later.

**Comment by gordonwoodhull** [comment] 2015-07-08 15:40
I think this must be pretty rare. Please comment if you are able to repro consistently.

**Comment by gordonwoodhull** [comment] 2015-10-07 14:49
Confirmed not reproducible. Closing.

**Closed by gordonwoodhull** 2015-10-07 14:49 UTC
Labels: bug, reviewed
