### ISSUE TITLE
Code contents are getting deleted after refreshing the page

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1459] opened 2015-05-21 05:10 UTC
It was observed in RCloud-2 as well as on Local instance, upload any large size CSV file to that notebook, then the uploaded file is displayed in asset div. When we refresh the page all the code present in that notebook are getting erased.

below are the screen shots.

1.Open a notebook, which contains some code in it

![1_before_uploading](https://cloud.githubusercontent.com/assets/10941328/7741791/5c110c1c-ffa2-11e4-8673-050613b782f5.PNG)

2.Now upload a CSV file ( i am uploading 6.8Mb size of CSV file) to that notebook, as we can see the  uploaded file is displayed in asset div

![1_after_uploading_csv](https://cloud.githubusercontent.com/assets/10941328/7741800/8ceecab8-ffa2-11e4-8434-84c5a9b64991.PNG)

3.Now refresh the page, all the code present in that notebook is erased

![1_afterrefreshingpage](https://cloud.githubusercontent.com/assets/10941328/7741810/a8cea9ec-ffa2-11e4-9652-cc7fb9eeed8b.PNG)

**Comment by gordonwoodhull** [comment] 2015-05-21 12:24
Yes, good find, although a duplicate of #1073, it's especially important now and should be dealt with for  1.4

**Closed by gordonwoodhull** 2015-05-21 12:24 UTC
