### ISSUE TITLE
Session div error while posting comments in comments div

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1513] opened 2015-06-17 07:27 UTC
This issue is observed in RCloud-5 (Compute separation/proxified) instance with commit (develop/34252d3).
When we post any comment in comments div, the comment doesn't get posted followed by the error message in session div

![comments_post](https://cloud.githubusercontent.com/assets/9251570/8201553/2e68aa96-14a0-11e5-90f8-a7321592f0c0.PNG)

However after page refresh the previously posted comment appears in the comments div

**Comment by gordonwoodhull** [comment] 2015-06-19 18:20
thanks @sanketd11

**Comment by gordonwoodhull** [comment] 2015-06-25 02:27
I'm not able to reproduce this. Looks like it would only happen with "subscribe to comments" enabled, but even when I set that manually (the option is gone on rcloud-5 because email is disabled), I don't get the error.

@sanketd11, are you still seeing this?

**Comment by gordonwoodhull** [comment] 2015-06-29 20:44
ping? I am guessing this was transient configuration problem.

**Comment by gordonwoodhull** [comment] 2015-07-08 15:40
I'm closing this - I assume this was a transient version mismatch between packages. Please comment if you see this again and I'll reopen.

**Closed by gordonwoodhull** 2015-07-08 15:40 UTC
Labels: bug, reviewed
