### ISSUE TITLE
add horizontal scroll bar to notebook area when there are plots?

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1239] opened 2015-02-04 10:29 UTC
Steps to replicate
1) Load any notebook which will generate graph in the output div (e.g. using 'plot' function)
2) Execute the notebook and generate graph output
3) click on the 'help' div

![g2](https://cloud.githubusercontent.com/assets/9251570/6038781/2c0ba406-ac86-11e4-9ffa-b6f51408fa0e.png)

![g1](https://cloud.githubusercontent.com/assets/9251570/6038794/42feec36-ac86-11e4-8285-9512377e530c.png)
This happens only for the graph outputs. In case of text outputs, the output text gets wrapped when help div is opened

**Comment by gordonwoodhull** [comment] 2015-02-04 14:48
Thanks for reporting this @sanketd11. 

However, this behavior goes back quite a while and I am inclined not to fix this.  Although we have horizontal scrollbars for search, it is generally kind of annoying to have two dimensions of scrolling.  It is always possible to hide side panels to see the entire plot.

Also, it would mean either not wrapping the text, or having it scroll out of view when scrolling to see the right side of a plot.  Finally, I don't think scrolling around a plot is useful - one needs to see the entire thing for it to be useful.

Does anyone else have an opinion about this?

**Comment by gordonwoodhull** [comment] 2015-02-14 16:19
I'm closing this. The current behavior is by design, as noted above.

**Comment by gordonwoodhull** [comment] 2015-02-22 04:28
I noticed that the compromise here is to scroll just the chart area, which we are already doing for dcplot.

**Comment by gordonwoodhull** [comment] 2015-02-22 04:29
Thanks @sanketd11, good suggestion.  I was thinking of scrolling the entire notebook area, which would be annoying, but if the plot isn't showing, why not scroll just that.

**Closed** 2015-02-23 15:00 UTC
Labels: enhancement, wontfix
