### ISSUE TITLE
don't say logged out if you weren't logged in

### ISSUE THREAD

**Issue by NaikPrateek** [att/rcloud#1704] opened 2015-10-06 07:56 UTC
steps to replicate:
1. Create a notebook and publish it
2. Logout and open the published notebook in view.html mode
3. Now click on edit icon
session reconnect message appears and in URL it shows "notebook=null".

**Comment by gordonwoodhull** [comment] 2015-10-07 14:29
Since the `notebook=null` is not reproducible, I'm going to repurpose this issue.

It should not say you've been logged out, it should send you directly to login.R if running view.html notebook anonymously and press edit button.

**Comment by gordonwoodhull** [comment] 2017-04-13 18:08
Duplicate of #1923

**Closed by gordonwoodhull** 2017-04-13 18:08 UTC
Labels: enhancement
