### ISSUE TITLE
Misleading Cell status for cell that calls locator() 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1687] opened 2015-10-01 09:46 UTC
This issue is observed on RCloud-5 instance. Following are the steps to replicate:
- Call the locator() in a cell next to R cell that contains plots
- Press stop button 
- Click for specified number of times

Sometimes blank output div is shown and sometimes it does show all the requested coordinates but still the cell status shows 'cell ran but had an error' ('!') instead of 'cell successfully ran' (green circle) status

![locator_rc5_stop_cell_status](https://cloud.githubusercontent.com/assets/9251570/10217713/9ff150ca-67ff-11e5-8a42-e627498904f1.PNG)

![locator_rc5_stop_cell_status1](https://cloud.githubusercontent.com/assets/9251570/10217714/9ff16632-67ff-11e5-8254-ddd6ac554540.PNG)

**Comment by s-u** [comment] 2015-10-01 15:20
This seems like a duplicate of #1685 to me - at least it's the same underlying issue that locators cannot be stopped other than by cancellng.

**Comment by gordonwoodhull** [comment] 2015-10-03 17:48
Agree

**Closed by gordonwoodhull** 2015-10-03 17:48 UTC
Labels: bug, duplicate
