### ISSUE TITLE
Discover page fails to display modified time

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#2297] opened 2016-10-06 12:18 UTC
Steps to replicate:
- Create a new notebook
- Make any existing(recently opened) Notebook as `Private`
- Now make that notebook as `Public` 
- Go to discover page
  Instead of showing recent modified time it displays last modified time.

![image](https://cloud.githubusercontent.com/assets/10941328/19151890/dfc6f3f0-8bec-11e6-9177-ea3aa566996c.png)

**Comment by gordonwoodhull** [comment] 2016-10-28 04:01
Seems like we might be displaying the created-time but sorting by the modified-time.

**Comment by gordonwoodhull** [comment] 2016-11-10 22:05
I am no longer seeing this. I wonder if we were initially storing bad data but it's slowly being replaced by good data? 

But that doesn't make sense because the sorting was correct, and the sort key is the data we store separately. The date we display comes from `rcloud.get_multiple_notebook_infos`, which hasn't changed in more than a year.

**Comment by gordonwoodhull** [comment] 2016-11-10 22:08
Duplicate of #2292

**Closed by gordonwoodhull** 2016-11-10 22:08 UTC
Labels: bug
