### ISSUE TITLE
Find field in view mode doesn't close on 'Esc' and 'Close'.

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2127] opened 2016-06-24 09:51 UTC
'Esc' and 'Close' is not working for find field.

Steps to Reproduce:
- Create new notebook.
- Press ctrl+f
- Press esc or Press 'X'

**Comment by shaneporter** [comment] 2016-06-24 09:54
Hi @amithrb - I can't reproduce this one. I am able to close the find field by pressing escape or clicking the 'x' at the top right.

**Comment by amithrb** [comment] 2016-06-24 11:11
@shaneporter , I was able to reproduce it. I will try and help to reproduce during WebEx call.

**Comment by shaneporter** [comment] 2016-06-24 11:12
Thanks. Strange that I can't reproduce it.

**Comment by gordonwoodhull** [comment] 2016-06-24 22:08
I'm not seeing this. Hopefully it got fixed by the series of fixes I just made for Firefox.

**Comment by Prateek032** [comment] 2016-06-27 05:01
for "view.html", i am able to reproduce it on both the browsers(chrome and firefox)

**Comment by gordonwoodhull** [comment] 2016-06-27 13:43
Confirmed, retitling. In addition, find (in view mode) is not updating when the find-text is changed. One has to change the focus away in order to see highlights updated.

**Comment by gordonwoodhull** [comment] 2016-06-27 13:48
Probably the same root cause as above, the source is also not shown until one changes the focus away and back.

@shaneporter, I did a fair amount of work on find & replace on friday (in order to get it working on Firefox), so I wouldn't be surprised if I introduced some of these issues. Please keep an eye out for things that were changed that shouldn't have been!

**Comment by shaneporter** [comment] 2016-06-27 14:50
It doesn't look quite right either:

![image](https://cloud.githubusercontent.com/assets/2493614/16383910/e7a728f0-3c7e-11e6-97ab-6cca17bf358b.png)

**Comment by shaneporter** [comment] 2016-06-27 15:30
PR #2141

**Closed** 2016-06-27 18:43 UTC
Labels: bug, Important
