### ISSUE TITLE
Aberrant behaviour of star count while forking Notebook folder

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1514] opened 2015-06-17 07:31 UTC
This issue was observed in RCloud-Local instance on latest Commit:6eb027af59b2be78bce1f6c866cf797d604eace9.
Following is the scenario to replicate
* Open other user's notebook folder from 'All notebooks' tree
* Click on Folder fork option, the respective folder with notebooks are displayed under 'My Notebook' tree with star count 1 like below

![1forkingfolder1](https://cloud.githubusercontent.com/assets/10941328/8201634/70b94428-14f0-11e5-91f0-f9a22df791cb.PNG)

* Now again click on the Folder fork option under 'All Notebook', the star counts are getting displayed as 0 under My notebook tree

![2forkingfolder2](https://cloud.githubusercontent.com/assets/10941328/8201640/79715344-14f0-11e5-867d-1ee035081397.PNG)

**Comment by gordonwoodhull** [comment] 2015-06-19 18:41
uh oh. thanks @Prateek032! this looks like a temporary glitch, because reloading RCloud causes the star numbers to return. I'm more concerned that the notebooks are not forked the second time, #1522 - probably related.

**Comment by gordonwoodhull** [comment] 2015-06-19 18:42
+1 for using the word "aberrant"!

**Comment by gordonwoodhull** [comment] 2015-08-11 22:31
I'm not able to reproduce this. Probably fixed by handling the case where GitHub does not let you fork a notebook a second time for #1522.

Please check with new commits.

**Comment by gordonwoodhull** [comment] 2015-08-19 19:01
I think this is fixed. Somehow we are returning to GitHub letting you fork a second time, which is weird. But the case where it didn't and the stars got stomped, I believe is fixed, so I'm closing this. 

Please comment if it recurs.

**Closed by gordonwoodhull** 2015-08-19 19:01 UTC
Labels: bug
