### ISSUE TITLE
backspace in find dialog invokes cell deletion instead

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1906] opened 2016-04-16 00:51 UTC
likewise in notebook title, comments, settings, etc. (this is on mac of course, i assume there is similar behavior for del on windows.)

all of these are regular edit boxes or contenteditable - we can't steal delete or backspace from them. probably the code in init.js that disables backspace as browser-back but leaves it enabled for various edit controls, could be put in a function and reused here.

**Comment by Prateek032** [comment] 2016-04-18 11:19
Same behavior on Ubuntu

**Comment by shaneporter** [comment] 2016-04-18 11:25
this should now be fixed by commit e694e6f

**Comment by sanketd11** [comment] 2016-04-25 09:32
This issue is still reproducible for Find/Replace dialog only

**Comment by sanketd11** [comment] 2016-04-28 05:09
Confirmed ! This issue still persist on  dcdb296

**Comment by shaneporter** [comment] 2016-04-28 12:58
Have just checked PR #1933, and that fixes this issue too. @gordonwoodhull - please could you review and verify? Thanks.

**Comment by gordonwoodhull** [comment] 2016-04-28 13:48
Ah yes I didn't merge that because I was too confused. Will look at it with fresh eyes.

**Comment by gordonwoodhull** [comment] 2016-04-28 17:58
fixed by #1933

**Comment by sanketd11** [comment] 2016-04-29 04:58
This issue is still out there in ff2aec4 (latest commit)

**Comment by gordonwoodhull** [comment] 2016-04-29 05:27
Uh oh, I tested the heck out of this, what's going on.

**Comment by shaneporter** [comment] 2016-04-29 08:26
I have ff2aec4 and I'm unable to reproduce the issue.

Just so I'm not missing something, here's what I do on Ubuntu 14.04/Chrome.

1. Select one or more cells in a notebook.
2. Invoke find with `ctrl` `f`.
3. Type a search string into the 'find' input.
4. Press the backspace key.
5. A character is removed. Nothing else happens.

:confused:

**Comment by shaneporter** [comment] 2016-05-10 08:21
@gordonwoodhull, @sanketd11 - I have the latest develop branch code and I'm not able to reproduce this issue. Given that recent shortcut code has been merged, can this issue be closed? Thanks.

**Comment by sanketd11** [comment] 2016-05-10 08:43
Confirmed ! This issue is no longer reproducible.

**Closed** 2016-05-10 08:51 UTC
Labels: bug
