### ISSUE TITLE
fork all notebooks in a folder/sub-tree

### ISSUE THREAD

**Issue by holyguster** [att/rcloud#1149] opened 2014-12-12 14:20 UTC
Folks have asked for the ability to easily fork all notebooks in a folder/sub-tree.

**Comment by gordonwoodhull** [comment] 2015-03-27 17:56
Thanks Marty, this is requested often. Will try to do this for 1.4. Duplicate of #1392

**Comment by gordonwoodhull** [comment] 2015-07-01 13:32
this proved to be too buggy for 1.4, delaying to 1.4.1

**Comment by gordonwoodhull** [comment] 2015-08-11 22:49
This wasn't as buggy as we thought, except that GitHub doesn't allow forking a gist a second time.

**Closed by gordonwoodhull** 2015-08-11 22:49 UTC
Labels: enhancement
