### ISSUE TITLE
Firefox: Inappropriate behaviour by invoking find and replace

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2074] opened 2016-06-14 11:07 UTC
Steps to reproduce:

Scenario 1:
1. In non editable mode press ctrl+h
2. Press esc
3. Press ctrl+f (invokes both find and replace fields)

Secnario 2:
1. In non editable mode press ctrl+f
2. Press esc
3. Press ctrl+h (invokes only find field)

**Comment by gordonwoodhull** [comment] 2016-06-22 14:57
Not able to repro on OSX. ctrl-opt-f always invokes browser's search feature. (meaning, we don't capture that key combo.)

**Comment by shaneporter** [comment] 2016-06-24 08:37
I can't reproduce on Firefox (Ubuntu). 

In both scenarios, ctrl+h is not enabled (so I see the history panel), and ctrl+f invokes find only.

@amithrb is it possible this has been fixed? Please can you try again? Thanks.

**Comment by amithrb** [comment] 2016-06-24 09:32
@shaneporter , I am able to reproduce it. Please try below scenarios:

Scenario 1:
- Create cell and make it non editable mode.
- Press ctrl+h
- Press esc
- Press ctrl+f (invokes both find and replace fields)

Scenario 2:
- Create cell and make it non editable mode.
- Press ctrl+f
- Press esc
- Press ctrl+h (invokes only find field)

**Comment by gordonwoodhull** [comment] 2016-06-24 22:01
Should be fixed by 1d08a505c17

**Closed by gordonwoodhull** 2016-06-24 22:01 UTC
Labels: Annoying, bug
