### ISSUE TITLE
eliminate @ from c-s deferred result strings

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud#1725] opened 2015-10-22 21:04 UTC
Starting a new conversation on #1676.

@s-u, would you object to changing this character, since it's unlikely that we'll fix pandoc's foolish assumption that anything with an `@` in it is an email address?

I think it's a safe change since
 - the output is transitory, only exists for a split second before it's replaced
 - we assume that RCloud client and server are running the same version always

Deferred result strings exist only for the sake of Markdown and RMarkdown, so I don't see why we shouldn't accommodate whatever syntactical limitations they give us, no matter how silly.

**Comment by s-u** [comment] 2015-10-22 21:16
Part of the problem is that we're simply passing the OCAP ID directly - and changing the ID that would require modification of Rserve and it has a bit of ripple effect - at least the proxy and rserve-js need to be changed accordingly so they need to be able to tell compute pass-through messages. So porbably a much safer measure would be to wrap/unwrap the IDs at the edge so we dont' need to make the change so deep...

**Comment by gordonwoodhull** [comment] 2015-10-22 21:21
Ah, I didn't realize it went deeper. So you're suggesting doing a `gsub

**Comment by s-u** [comment] 2015-10-22 21:30
Heh, right.

But note that the JS side has to undo this change before resolving and/or creating the OCAP reference on its side! May it could actually do an unconditional `s/^!/@/` when OCAPs are resolved just to make sure we don't miss something and we have to remember never to use `!` prefix for something else :P

**Comment by gordonwoodhull** [comment] 2015-10-22 21:54
Okay, I'll take this - scheduling for 1.5.1 because interactives in markdown are currently pretty broken.

**Closed** 2015-10-23 18:06 UTC
Labels: enhancement
