### ISSUE TITLE
Errors on booting a fresh rcloud deployment on Ubuntu 14.04

### ISSUE THREAD

**Issue by cscheid** [att/rcloud#1284] opened 2015-02-09 22:51 UTC
After following the installation instructions, I get the following error on the session pane

![image](https://cloud.githubusercontent.com/assets/285675/6117627/10f2b7c2-b073-11e4-8377-784b8e65b0de.png)

The error regardling error handling seems to come from `htdocs/js/rclient.js`, line 96. It seems that the error being posted there is a list (in my case, `["URI malformed", undefined]`), while the handler expects an object with a message field.

But the error itself doesn't seem to be the problem. Rather, it's the "Error in split.default(results...)" part. Unfortunately I don't have a stack trace from R to keep going.

**Comment by cscheid** [comment] 2015-02-09 22:53
This is the console output on Chrome, which includes Bluebird's long stack trace.

![image](https://cloud.githubusercontent.com/assets/285675/6117701/c9c1ccfc-b073-11e4-890b-698b23679cbc.png)

**Comment by sanketd11** [comment] 2015-02-11 10:05
Same issue is faced on Ubuntu 12.04

**Comment by gordonwoodhull** [comment] 2015-02-11 10:37
another error handling thing. assigning those to you for now, @s-u.

**Comment by s-u** [comment] 2015-02-11 19:56
The error is a red herring (now fixed) - it has nothing to do with the failure. It must be something from `Promise.all` call since this is a array of two with the first one including the error, but I'm not enough of a bluebird wiz to be able to detangle the promises where this comes from. It is reproducible if you start with n empty RCS.

**Comment by gordonwoodhull** [comment] 2015-02-11 20:24
Sure, I guess that is me. Been wanting to try an ubuntu install.

**Comment by s-u** [comment] 2015-02-11 20:59
I don't think this has anything to do with ubuntu or the system - I suspect it's just about having an empty RCS.

**Comment by gordonwoodhull** [comment] 2015-02-12 14:56
@s-u, this appears to be due to the vectorizing in 49537e8117c49c5ee1651b1e0d5ff1dce86320eb

probably the malformed uri is to redis.

```
    at Object.RCloud.promisify_paths.v [as get_multiple_notebook_star_countsAsync] (http://135.197.226.172:8080/js/rcloud_bundle.js:136:31)
    at Object.rcloud.stars.get_multiple_notebook_star_counts (http://135.197.226.172:8080/js/rcloud_bundle.js:379:39)
    at http://135.197.226.172:8080/editor_tab.js:425:50
From previous event:
    at load_everything (http://135.197.226.172:8080/editor_tab.js:411:24)
    at Object.result.init (http://135.197.226.172:8080/editor_tab.js:1030:27)
```

I would fix but I don't have an empty RCS to test with.

**Closed** 2015-02-12 16:29 UTC
Labels: bug

**Comment by s-u** [comment] 2015-02-12 16:30
Thanks for teasing out the right call, yes, that was it! Asking for an empty notebook list returned one empty entry instead of an empty list.
