### ISSUE TITLE
Gitgist: Deleting all the contents of any asset file throws error in session div

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1398] opened 2015-03-31 07:26 UTC
When for any asset file, all the contents of that file are deleted, the error is thrown in session div

![asset](https://cloud.githubusercontent.com/assets/9251570/6914079/ecc653e6-d754-11e4-83fb-aced57397d38.PNG)

steps to replicate :
* Create any asset in assets div
* Delete all the contents from that asset 
* Click on save icon

The above error message is displayed for any operations in assets div until that empty asset is deleted

This issue can also be replicated in RCloud instance linked to github.

**Comment by holyguster** [comment] 2015-03-31 18:29
Hi Gordon,

Might this be related to this old issue?

https://github.com/att/rcloud/issues/653

Gus

**Comment by gordonwoodhull** [comment] 2015-03-31 18:30
Thanks @holyguster, yes, this is a duplicate of #653

**Closed by gordonwoodhull** 2015-03-31 18:30 UTC
