### ISSUE TITLE
Check box remains selected even after cell deletion

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1833] opened 2016-03-11 04:42 UTC
select "All' from  the check box or just click on check box, cell gets selected
![celldelete](https://cloud.githubusercontent.com/assets/10941328/13693445/1b086544-e700-11e5-9c08-0b92091cdb7d.PNG)

Now click on delete, the cell gets deleted but check box remains selected

![celldelete1](https://cloud.githubusercontent.com/assets/10941328/13693488/88f9c034-e700-11e5-9671-3e72dc199ba7.PNG)

**Comment by gordonwoodhull** [comment] 2016-03-11 13:44
I think this is a duplicate of #1834

**Comment by gordonwoodhull** [comment] 2016-03-11 13:44
At least, covering another side of the same issue.

**Closed by gordonwoodhull** 2016-03-11 13:44 UTC
