### ISSUE TITLE
Selected word should populate the Find/Replace field 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1846] opened 2016-03-17 05:03 UTC
When Find/Replace feature is invoked, the currently selected words should populate in the Find/Replace field.

**Comment by shaneporter** [comment] 2016-05-18 15:15
To clarify, if there is a selection when the user invokes _find_ or _replace_ it should be used as the default text in the **_find_** field.

**Comment by shaneporter** [comment] 2016-05-18 15:39
![image](https://cloud.githubusercontent.com/assets/2493614/15365079/cfdf5b16-1d16-11e6-9795-30a530ecb20f.png)

Multiple cells, multiple selections. Cursor in a different cell.

What should be used for the 'selected text' in this case? Should selection === selected text in cell that has current focus? Feels kludgy. :neutral_face:

**Comment by gordonwoodhull** [comment] 2016-05-18 20:52
That makes sense to me, it's not really a selection across cells in this case. The copy command would not look at other input elements for example.

The case where no cell is active, and the selection spans multiple cells: that's more ugly. But I think we should be literal there too.

**Comment by shaneporter** [comment] 2016-06-01 16:28
Having spoken with @gordonwoodhull earlier, it was agreed that 'selected text' should be the active cell's selected text.

**Comment by Prateek032** [comment] 2016-06-03 05:18
For editable cells the selected words are getting reflected in 'Find' text filed but for the non editable cells it is not working

**Comment by gordonwoodhull** [comment] 2016-06-03 06:47
Ah. Good point @Prateek032. If no cell has the focus then the current selection at the document level should populate the dialog instead. 

[There is code that looks at the document - level selection for the clipboard copy command in order to not copy non cell content](https://github.com/att/rcloud/blob/develop/htdocs/js/ui/init.js#L71-88). It could be reused, since we're basically doing an implicit copy here.

**Comment by gordonwoodhull** [comment] 2016-06-06 19:48
fixed by #2037

**Comment by Prateek032** [comment] 2016-11-07 10:40
on the latest commit 35cf446, selected text in not populating in Find text field

**Comment by gordonwoodhull** [comment] 2016-11-07 23:16
Confirmed, thanks @Prateek032, reopening.

**Comment by gordonwoodhull** [comment] 2016-11-11 02:16
This was broken by 9f5e769ad14, a very complicated commit having to do with find next/previous. 

Find next / find previous needs to proceed to the next or previous only if the highlights are already shown (search is active). However this commit also disabled the logic copying the selected text into the find input, in that same case.

**Closed** 2016-11-11 02:49 UTC
Labels: enhancement
