### ISSUE TITLE
file completion appends paths instead of replacing them

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1645] opened 2015-08-19 13:35 UTC
![screen shot 2015-08-19 at 9 39 43 am](https://cloud.githubusercontent.com/assets/2073427/9357668/424914fa-4656-11e5-8172-b51c9f06ee8f.png)

Hit Enter:

![screen shot 2015-08-19 at 9 38 26 am](https://cloud.githubusercontent.com/assets/2073427/9357637/185b7bb0-4656-11e5-8911-072c924212d5.png)

**Comment by s-u** [comment] 2015-08-19 13:41
[BTW: note that the highlighting is wrong - the whole prefix should be highlighted instead of the random letters, and the superfluous slash]

**Comment by gordonwoodhull** [comment] 2015-08-19 13:49
I didn't know R would also match paths, and Ace is apparently unaware of this possiblity as well.

As noted in #1617, Ace is relying on a regex in order to search backward and match any replacement text. Right now I'm wondering if this should just be `/./` because it seems R is willing to replace just about anything.

**Comment by s-u** [comment] 2015-08-19 15:11
Well, R actually tells you exactly which part to replace (both the start point and the content) - so ideally, ACE shouldn't be guessing, but just replace what it's told to. It's impossible to use regexp to guess that since it depends on the context (symbols, files, ...) so the regexp would have to change.

So is there a way to tell ACE what to highlight and replace? Then we would simply use `$token` for the highlighting and `$start` to denote where to replace from.

**Comment by gordonwoodhull** [comment] 2015-08-19 15:14
yes, i am sure we could always dig deeper into the ace source........

**Comment by s-u** [comment] 2015-08-19 15:20
Heh, so what you mean is "no, there is no API for that" ...

**Comment by gordonwoodhull** [comment] 2015-08-19 15:22
Or, "I can't tell where the API ends and the library begins."

**Comment by gordonwoodhull** [comment] 2016-04-19 20:19
@shaneporter, I'm assigning you some wild ace hacking in a few issues. If this is too much or if I can offer pointers, please let me know. I've learned and forgotten this stuff a few times now.

**Comment by shaneporter** [comment] 2016-04-27 10:34
@gordonwoodhull I start typing a path in the prompt area, but the editor doesn't offer any suggestions. I guess I'm doing something wrong.

**Comment by gordonwoodhull** [comment] 2016-04-27 10:41
Completion is assigned to tab and ctrl-. - is this this missing clue?

**Comment by shaneporter** [comment] 2016-04-27 10:42
Great - got it. Thanks.

**Comment by shaneporter** [comment] 2016-05-06 11:26
The double slashes are coming back from R.

**Comment by gordonwoodhull** [comment] 2016-05-06 12:20
That's not the problem, though. The problem is that it's pasting a second copy of the whole path instead of completing it in place.

I think it is not searching far enough backward. It's kind of a stupid implementation, when it gets a replacement it searches backward in the text for a match because it doesn't know how much to replace. So it doesn't use the position information that @s-u mentions, which would be much more accurate.

To be fair, probably other languages' replacement mechanisms don't return as much information.

Somewhere there is a regexp which it uses to search back. I've had to add characters to it but it's still not enough. @s-u's suggestion should fix it for once and for all.

**Comment by gordonwoodhull** [comment] 2016-05-06 12:23
I guess the highlighting problem is due to the regexp needing  to match slash - it thinks that only "co" could be replaced. And it thinks we might get discontinuous matches.

**Closed** 2017-10-13 19:50 UTC
Labels: bug
