### ISSUE TITLE
Bunch of functions in the environment viewer pane when running python

### ISSUE THREAD

**Issue by prateek05** [att/rcloud#1173] opened 2015-01-07 21:03 UTC
Run a python cell say print("Hello World")
Enviewer Pane:
Functions
RC.auth.anonymous	function
RC.authenticate	function
authenticated.ocaps	function
make.oc	function
unauthenticated.ocaps	function

**Comment by gordonwoodhull** [comment] 2015-02-14 06:06
Ever see this again @prateek05 ?

**Comment by gordonwoodhull** [comment] 2015-02-18 20:02
Closing due to non-reproducibility.

**Closed by gordonwoodhull** 2015-02-18 20:02 UTC
Labels: python
