### ISSUE TITLE
Unable to fork other user's notebook folder more than once

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1545] opened 2015-06-24 13:12 UTC
While forking the Notebook tree/folder belonging to other users, the fork operation takes place for once only. If try to fork that same notebook tree/folder repetitively, it does nothing however multiple copies of that folder with same folder name and incremented postfix is expected .

**Comment by gordonwoodhull** [comment] 2015-06-24 14:06
Thanks @sanketd11 - I noticed this too but I guess I didn't file a bug.

**Comment by gordonwoodhull** [comment] 2015-08-07 22:02
duplicate of #1522

**Closed by gordonwoodhull** 2015-08-07 22:02 UTC
Labels: bug, duplicate
