### ISSUE TITLE
Firefox: On clicking ESC, unable to close invoked find/replace feature

### ISSUE THREAD

**Issue by amithrb** [att/rcloud#2215] opened 2016-07-29 11:15 UTC
Unable to close invoked find/replace feature, on clicking ESC button.
This issue is not reproducible on rcloud-5 and rcloud social but able to reproduce on local instance.

Steps to Reproduce:   
- Add contents to the cell
- Make cell non editable
- Invoke find/replace option
- Close find/replace option using ESC or Close option
- Click anywhere on the screen, contents gets highlighted
- Once again invoke find/replace option
- Now, try to close invoked find/replace feature using ESC

**Comment by gordonwoodhull** [comment] 2016-07-29 11:40
Thanks @amithrb. In the fifth step, do you mean "click on the cell" instead of "click anywhere on the screen"? I'm not sure what you mean by "contents get highlighted".

**Comment by Prateek032** [comment] 2016-07-29 11:59
@gordonwoodhull , After closing  **Find/Replace**, click on cell/ any where on the screen. 
Contents are getting highlighted 

![image](https://cloud.githubusercontent.com/assets/10941328/17247557/a1390388-55b1-11e6-9f68-02c9a1b8eb2a.png)

**Comment by gordonwoodhull** [comment] 2016-07-29 12:07
Thanks @Prateek032. I see it now.

**Comment by gordonwoodhull** [comment] 2016-09-07 14:39
I see the highlight problem (#2214) but was not able to repro ESC not closing the dialog. It makes sense that it could be caused by the recently-used menu, so I'm going to trust that #2251 fixes this.

**Closed by gordonwoodhull** 2016-09-07 14:39 UTC
Labels: bug, firefox
