### ISSUE TITLE
Changing permissions to a notebook propagates differentially

### ISSUE THREAD

**Issue by martymcwizard** [att/rcloud#1506] opened 2015-06-15 20:57 UTC
Recently a user put their database password into a notebook.  I urged them to make their notebook private.  In the notebook tree the name of their notebook turned gray for me, however when I hit refresh the notebook continued to load.  When I left and opened another notebook and then came back I could still load the private notebook.  Only when I closed that tab of the browser and reopened (I did not have to log back in) did the notebook finally disappear from the tree.

**Comment by gordonwoodhull** [comment] 2015-06-15 21:04
Right, the earlier idea of private notebooks was just to hide them from the tree, it didn't prevent anyone else from reading the notebook (and I think there were issues with it being searchable as well). 

The notebook protections in 1.4 are more appropriate for a use-case like this. If you don't encrypt it and you're storing it on github, it's fair game if anyone ever learns the notebook id.

**Comment by gordonwoodhull** [comment] 2015-06-19 18:55
i would argue this is not a bug, just expecting more of private notebooks than they actually do.

i will close this and encourage people to use the "real" private notebooks when they come along.

**Closed by gordonwoodhull** 2015-06-19 18:55 UTC
