### ISSUE TITLE
Proxified RCloud: Output of Rpython-2 commands is not displayed 

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1423] opened 2015-04-27 08:04 UTC
For any cell containing Rpython2 commands, when that cell is executed,executed status as Green circle is displayed after execution but the output is not displayed in either output div or session div.                In RCloud-2/RCloud local, the output is displayed in sessions div.
Similarly, No output is displayed in 'view.html' mode for all RCloud instances

![rpython-2](https://cloud.githubusercontent.com/assets/9251570/7343668/30474f7e-ec92-11e4-95f3-03af392fdc66.PNG)

**Comment by s-u** [comment] 2015-05-12 21:13
This is duplicate of #1430

**Closed by s-u** 2015-05-12 21:13 UTC
