### ISSUE TITLE
notebooks with binary assets exported improperly

### ISSUE THREAD

**Issue by Prateek032** [att/rcloud#1475] opened 2015-06-10 09:32 UTC
Export a notebook with binary assets to a file, import the gist file. 

The following error is displayed in session div

![import_gistfile](https://cloud.githubusercontent.com/assets/10941328/8079302/341a2524-0f81-11e5-8d79-f5d17c92e5b2.PNG)

**Comment by gordonwoodhull** [comment] 2015-06-10 15:17
I think we may be able to export the raw notebook (with base64-encoded assets) as text. 

This mainly means exposing `.rcloud.get.notebook` instead of `rcloud.get.notebook`.

@s-u, do you see a problem with this approach?

**Comment by s-u** [comment] 2015-06-10 17:17
No

The only issue with generating a notebook structure in json is that it's not well-defined - we simply pass what we get from GH, but with the advent of multiple gist back-ends it would actually make sense to define the format and adhere to it (there is a lot of crud from GH that we don't actually use so that would be preferably filtered out). But that's a whole another discussion...

**Comment by s-u** [comment] 2015-06-10 17:18
BTW: we may want to fix `rcloud.create.notebook` anyway since it would be capable of using the filtering just as `rcloud.update.notebook` does so that may be the actual bug here regardless of the format we choose ...

**Comment by gordonwoodhull** [comment] 2015-06-12 19:47
Right now we "sanitize" the notebook on writing it, basically by whitelisting a couple of keys. I think it is a valid approach. But it's not expecting `content` to be an object:

```
{"description":"Notebook 1","files":{"scratch.R":{"content":"# keep snippets here while working with your notebook's cells"},"foo.png":{"content":{"r_type":"raw"}}}}
```

**Comment by s-u** [comment] 2015-06-12 20:09
Yes, that's the bug I meant - `rcloud.create.notebook` fails to call `.gist.binary.process.outgoing()` and passes the raw object directly to the gist API which is invalid.

**Comment by gordonwoodhull** [comment] 2015-06-12 20:10
Ah you are referring to the bug I am about to encounter after I fix the first one. That is uncanny.

**Comment by gordonwoodhull** [comment] 2015-06-12 20:18
Or rather, you are referring to the root cause of #1470. This one is fixed by outputting the "raw" (as in what-github-sees) content. Will look at #1470 next, thanks for the hint!

**Closed** 2015-06-12 22:44 UTC
Labels: bug
