### ISSUE TITLE
Inappropriate search result counts after paginating 

### ISSUE THREAD

**Issue by prateek032** [att/rcloud#1722] opened 2015-10-21 07:44 UTC
When we search with 'RCloud' keyword it display like below

![1befor_paginating](https://cloud.githubusercontent.com/assets/10941328/10630587/9264ec90-77a5-11e5-9cd6-10dc184a99e1.PNG)

at some point after paginating it display inappropriate count 

![11after](https://cloud.githubusercontent.com/assets/10941328/10630609/c0d714d6-77a5-11e5-8836-4136e0564eb6.PNG)

**Comment by s-u** [comment] 2015-10-27 14:14
Yes, that is a known issue caused by the way paginating works in SOLR (since all pages from lakes are independent of each other, the moment you get beyond the results of one lake there is no information on that lake anymore).

I don't think result pagination has a chance of being re-worked anytime soon since proper solution requires aggregating SOLR instance or a different approach to search.

**Comment by gordonwoodhull** [comment] 2017-11-29 17:57
Fixed with the search reworking in RCloud 1.9

**Closed by gordonwoodhull** 2017-11-29 17:57 UTC
Labels: solr
