### ISSUE TITLE
asset HTML mode

### ISSUE THREAD

**Issue by GanapatiBhat** [att/rcloud#943] opened 2014-10-18 15:26 UTC
Loaded HTML file as an asset which has got script block on it. When  I try to bulk comment few lines of code using 'CTRL+/ ' it is not working. However it works fine in .js files. 

Also .HTML files doesn't appear formatted, i mean different HTML tags are not highlighted as compared to other HTML editors, however .js files look better

**Comment by gordonwoodhull** [comment] 2015-04-30 22:21
duplicate of #1387

**Closed by gordonwoodhull** 2015-04-30 22:21 UTC
Labels: enhancement
