### ISSUE TITLE
execution timestamps and/or elapsed times in cell headers

### ISSUE THREAD

**Issue by s-u** [att/rcloud#1926] opened 2016-04-21 12:24 UTC
Occasionally, when running longer jobs unattended it is useful to know how long a cell was running and when it finished. For that purpose it would be nice to have timestamp and/or elapsed time. Probably the most intuitive and unobtrusive place would be the cell header.

**Comment by gordonwoodhull** [comment] 2016-04-21 14:10
Duplicate of #1158, which notes this can probably be implemented as an extension.

**Closed by gordonwoodhull** 2016-04-21 14:10 UTC
Labels: enhancement

**Comment by s-u** [comment] 2016-04-21 17:11
That above is related, but different - I wasn't talking about benchmarking, but simple wall-clock so you know if the job took and hour or 5 mins - and that is language-independent.

**Comment by gordonwoodhull** [comment] 2016-04-21 17:27
Hmm, maybe the applications are different, but it looks like the same feature to me. 

It's just a matter of watching the cell state "light" and starting/stopping a stopwatch based on it. Looks like there's a little bit of work of exposing that state as an event, then this could be an extension (or at least it doesn't have to be crammed into cell_view.js). Adding UI elements to the cell headers via extensions is pretty simple.
