### ISSUE TITLE
Unable to remove admin/member from group

### ISSUE THREAD

**Issue by sanketd11** [att/rcloud#1570] opened 2015-06-26 08:29 UTC
This issue is observed on RCloud-5. For an admin of any group, he is not able to remove any member or other admin from that group. The error message shows "empty reply from server". However admin is able to add new admins as well as new members.

**Comment by gordonwoodhull** [comment] 2015-06-26 13:54
Confirmed. The full stack trace is:

```
Error: protection.remove_cryptgroup_user: Error in function (type, msg, asError = TRUE)  : Empty reply from server
R trace:
fun(structure(list(message = msg, call = sys.call()), class = c(typeName, 
    "GenericCurlError", "error", "condition")))
function (type, msg, asError = TRUE) 
{
    if (!is.character(type)) {
        i = match(type, CURLcodeValues)
        typeName = if (is.na(i)) 
            character()
        else names(CURLcodeValues)[i]
    }
    typeName = gsub("^CURLE_", "", typeName)
    fun = (if (asError) 
        stop
    else warning)
    fun(structure(list(message = msg, call = sys.call()), class = c(typeName, 
        "GenericCurlError", "error", "condition")))
}(52L, "Empty reply from server", TRUE)
.Call("R_curl_easy_perform", curl, .opts, isProtected, .encoding, 
    PACKAGE = "RCurl")
curlPerform(curl = curl, .opts = opts, .encoding = .encoding)
RCurl::getURL(paste0(getConf("session.server"), request))
.session.server.request(paste0("/mod_group?token=", URIencode(token), 
    "&realm=", URIencode(realm), "&group=", URIencode(group), 
    action))
strsplit(.session.server.request(paste0("/mod_group?token=", 
    URIencode(token), "&realm=", URIencode(realm), "&group=", 
    URIencode(group), action)), "\n", TRUE)
session.server.modify.group("rcloud", .session$token, groupid, 
    remove = user)
fun(...)
```

**Comment by s-u** [comment] 2015-06-26 13:59
duplicate of #1536

**Closed by s-u** 2015-06-26 13:59 UTC
Labels: bug

**Comment by gordonwoodhull** [comment] 2015-06-26 14:48
Restarted the SKS server and the feature is working properly.
